FROM ubuntu:latest
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install openjdk-8-jdk wget
RUN apt-get -y install openssh-client
RUN apt-get install -y vim
RUN apt-get install -y git
RUN apt-get install docker.io -y
RUN git clone https://Shalini1989:Shalini2018@github.com/Shalini1989/SpringMvcSecurity.git
RUN mkdir /usr/local/tomcat
RUN wget http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.30/bin/apache-tomcat-8.5.30.tar.gz -O /tmp/tomcat.tar.gz
RUN apt-get update
RUN cd /tmp && tar xvfz tomcat.tar.gz
RUN cp -Rv /tmp/apache-tomcat-8.5.30/* /usr/local/tomcat/
EXPOSE 8080
CMD /usr/local/tomcat/bin/catalina.sh run
RUN wget http://mirrors.jenkins.io/war-stable/latest/jenkins.war -O /tmp/jenkins.war
RUN apt-get update
RUN cp -Rv /tmp/jenkins.war /usr/local/tomcat/webapps/
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
ENV JENKINS_HOME /var/lib/jenkins
COPY security.groovy /var/lib/jenkins/init.groovy.d/security.groovy
COPY jenkins/plugins /var/lib/jenkins/
############################################################
ENV AWS_ACCESS_KEY_ID AKIAIAE32U66OXGDM6YQ
ENV AWS_SECRET_ACCESS_KEY 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
ENV S3_BUCKET outputs3jenkins
ENV AWS_DEFAULT_REGION us-east-1
RUN echo $AWS_ACCESS_KEY_ID
RUN echo $AWS_SECRET_ACCESS_KEY
RUN echo $S3_BUCKET
RUN echo $AWS_DEFAULT_REGION
################################################################
################################################################
#Install Maven #
RUN cd /usr/share/
RUN wget http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
RUN tar -xvzf apache-maven-3.3.9-bin.tar.gz
RUN mv apache-maven-3.3.9 apache-maven
ENV M2_HOME=/usr/share/apache-maven
ENV PATH=${M2_HOME}/bin:${PATH}
#RUN vi /etc/profile.d/mavenenv.sh
###############################################################################
############################################################################
 apt-get install zip
 apt-get install awscli -y